Base url mapping
briefmnews/django-esidoc pull request #17
Opened 2021-01-07 07:49 UTC by cirotix

I think that a dictionary lookup is more pythonic and declarative than a series of ifs.

I have not changed the logic, but I am wondering why there is a fallback on ENT_HDF_BASE_URL. Wouldn't it be better to explicitly lookup for HDF and let the exception raise if there is no base URL for a given ent?

2021-01-07 09:01 UTC, ThomSawyer requested changes

2021-01-07 09:01 UTC, ThomSawyer commented on django_esidoc/utils.py
> +}
I think you are right. The dictionnary is better.

Regarding your comment on the fallback I agree with you.
We'll need to add `"HDF": ENT_HDF_BASE_URL,` to the `BASE_URLS` constant.

2021-02-08 12:34 UTC, ThomSawyer approved these changes
I agree this is better.

The fallback on `ENT_HDF_BASE_URL` is solved by your commits.

I think we should separate e-sidoc from the other ENTs and have two distinct apps. This is a matter for another time but I'd like to know what you think about it?

2021-02-08 12:37 UTC, merged

2021-02-08 12:39 UTC, cirotix commented
> I think we should separate e-sidoc from the other ENTs and have two distinct apps. This is a matter for another time but I'd like to know what you think about it?

Yes, probably but I don't know if it worth the pain or not. (I don't know because I have not studied it or not, not that I say that I have a doubt)